[package]
name = "de_spawner"
description = "Object spawning, drafting and construction in Digital Extinction."

version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[features]
godmode = []

[dependencies]
# DE
de_audio.workspace = true
de_core.workspace = true
de_energy.workspace = true
de_index.workspace = true
de_map.workspace = true
de_messages.workspace = true
de_multiplayer.workspace = true
de_objects.workspace = true
de_pathing.workspace = true
de_terrain.workspace = true
de_types.workspace = true


# Other
ahash.workspace = true
bevy.workspace = true
parry2d.workspace = true
parry3d.workspace = true
