[package]
name = "de_uom"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/DigitalExtinction/Game"

[dependencies]
thiserror = "1.0"

[dev-dependencies]
approx = "0.5.1"
