[package]
name = "de_index"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/Indy2222/Digital-Extinction"

[dependencies]
# DE
de_core = { path = "../core", version = "0.1.0-dev" }

# Other
bevy = "0.7.0"
glam = "0.20.2"
iyes_loopless = "0.5.1"
parry3d = "0.9.0"
parry2d = { git = "https://github.com/Indy2222/parry", branch = "feature/dilation" }
ahash = "0.7.6"
nalgebra = { version = "0.31.0", features = ["convert-glam020"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "ray"
harness = false
