[package]
name = "de_loader"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/DigitalExtinction/Game"

[dependencies]
# DE
de_core = { path = "../core", version = "0.1.0-dev" }
de_map = { path = "../map", version = "0.1.0-dev" }
de_terrain = { path = "../terrain", version = "0.1.0-dev" }
de_objects = { path = "../objects", version = "0.1.0-dev" }
de_camera = { path = "../camera", version = "0.1.0-dev" }

# Other
bevy = "0.7.0"
iyes_loopless = "0.5.1"
iyes_progress = { version = "0.3.0", features = [ "iyes_loopless" ] }
futures-lite = "1.11"
