[package]
name = "de_movement"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/DigitalExtinction/Game"
keywords = ["DigitalExtinction", "gamedev", "game", "bevy", "3d"]
homepage = "https://de-game.org/"
description = "Digital Extinction entity movement, local dynamic obstacle avoidance, kinematics and similar."
license = "GPL-3.0"
categories = ["games"]

[dependencies]
# DE
de_core = { path = "../core", version = "0.1.0-dev" }
de_objects = { path = "../objects", version = "0.1.0-dev" }
de_pathing = { path = "../pathing", version = "0.1.0-dev" }
de_index = { path = "../index", version = "0.1.0-dev" }

# Other
bevy = "0.8"
iyes_loopless = "0.7"
parry3d = "0.9.0"
parry2d = { git = "https://github.com/Indy2222/parry", branch = "feature/dilation" }
