[package]
name = "de_tools"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/DigitalExtinction/Game"

[dependencies]
gltf = "1.0"
parry3d = "0.9.0"
clap = { version = "3.2.6", features = ["derive"] }
