[package]
name = "de_core"
description = "Various simple core utilities, structs, and so on for Digital Extinction."

version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
serde.workspace = true
bevy.workspace = true
iyes_loopless.workspace = true
iyes_progress.workspace = true
glam.workspace = true
nalgebra.workspace = true
parry2d.workspace = true
parry3d.workspace = true
enum-map.workspace = true
